### ISSUE TITLE
Pip's upgrade to 19.3 on 10/14 breaks bolt entirely

### ISSUE THREAD

**Issue by openbrian** [abantos/bolt#108]
Pip moved the location of main from pip._internal.main to pip._internal.main.main.  This breaks bolt entirely due to top level code in bolt_pip.py which executes merely by importing the task in _btapp.py.

**Comment by openbrian** [comment]
And this is already fixed.  Thanks @CurroRodriguez !  Side note I'm using pipenv with the pypi.org source.

**Comment by CurroRodriguez** [comment]
Yeah! We ran into the issue ourselves. I actually fixed it so it won't impact us in the future because this is the second time they do that in less than a year. I should be fine moving forward. Thanks for using bolt.

**Comment by CurroRodriguez** [comment]
This should be solved with version 0.3.1 and higher.
