### ISSUE TITLE
Nose is broken in 3.12

### ISSUE THREAD

**Issue by ALinck** [abantos/bolt#118]
Nose is not compatible with Python 3.12. There is an updated version called pynose that fixes the issue and is compatible from python 3.6.

**Comment by ALinck** [comment]
I was working off of a much older version somehow. Disregard

**Comment by CurroRodriguez** [comment]
@ALinck  Nice to see you're still using bolt.

**Comment by ALinck** [comment]
@CurroRodriguez Glad to see you're still maintaining it.
